### ISSUE TITLE
Install extras as separate packages?

### ISSUE THREAD

**Issue by asford** [conda-forge/dvc-feedstock#160]
This `dvc` package is (intentionally) heavily batteries-included and pulls in all the DVC extras as explicit requirements. This is great for zero-muss installations on conda, however it causes problems in environments where we may need to render a more minimal set of external dependencies.

Judging from DVC's [setup.py](https://github.com/iterative/dvc/blob/master/setup.py) and [Installation Instructions](https://dvc.org/doc/install/linux), the remote storage extras are *just* additional package requirements and don't modify the files packaged by DVC.

Would you be willing to refactor this package to allow a "no-extras" installation mode? This could be tackled through a multi-output build recipe that generates a `dvc` [metapackage](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#implicit-metapackages) for the top-level "all-remotes" build, with a `_dvc-core` primary packages and `_dvc-[extra]` packages for each remote extra.

**Comment by efiop** [comment]
Hi @asford !

We would be glad to split it up in some way that makes sense. I really like your idea with `dvc`(all in one) + `_dvc-core`(or maybe just `_dvc`, since it is pretty standalone) + `_dvc-[extra]`s. That's really neat! :sparkles:

Are there any side-effects to expect from such a split? Or is it really as good as it seems and won't affect the regular happy path of `conda install -c conda-forge dvc` for people that don't care?

**Comment by asford** [comment]
I've opened #161 for this proposed solution. This maintains the all-remote happy path via `conda install -c conda-forge dvc`, and I've tested that this support my mildly persnickety use case via `conda install -c conda-forge _dvc _dvc-s3`.

It *might* be worth opening a follow-up in the DVC docs after this merges?
